import type { OperationsSnapshot } from "../types.ts";

export const OPERATIONS_RAW_PROMPT_SENTINEL = "RAW_PROMPT_MUST_NOT_RENDER";

function collection(total: number, shown = total) {
  return { total, shown, truncated: shown < total };
}

export function createOperationsTestSnapshot(now = Date.now()): OperationsSnapshot {
  return {
    schema: "openclaw.operations-room.v2",
    generatedAt: now,
    snapshotId: "operations-e2e-snapshot",
    freshness: {
      status: "fresh",
      observedAt: now,
      staleAfterMs: 60_000,
      sources: {
        agents: { status: "available", observedAt: now },
        tasks: { status: "available", observedAt: now },
        workflows: { status: "available", observedAt: now },
        schedules: { status: "available", observedAt: now },
        capabilities: { status: "available", observedAt: now },
        models: { status: "available", observedAt: now },
        processes: { status: "available", observedAt: now },
        event_loop: { status: "available", observedAt: now },
        monitor: { status: "available", observedAt: now },
        incident_ledger: { status: "available", observedAt: now },
      },
    },
    completeness: { status: "complete", unavailableSources: [], fallbackSources: [] },
    briefing: {
      tone: "attention",
      text: "One issue is being handled while one agent verifies the Operations Room.",
    },
    qualityTarget: 93,
    qualityScore: 96,
    overallStatus: "degraded",
    summary: {
      agents: 4,
      workingAgents: 1,
      attentionAgents: 1,
      tasks: 2,
      activeTasks: 1,
      failedTasks: 0,
      workflows: 1,
      activeWorkflows: 1,
      cronJobs: 1,
      failingCronJobs: 0,
      plugins: 1,
      skills: 1,
      tools: 1,
      models: 1,
      findings: 2,
      actionableFindings: 1,
      historicalFindings: 1,
      needsUserFindings: 0,
      handlingFindings: 1,
      watchingFindings: 0,
      criticalFindings: 0,
    },
    collections: {
      agents: collection(4),
      tasks: collection(2),
      workflows: collection(1),
      cronJobs: collection(1),
      skills: collection(1),
      plugins: collection(1),
      tools: collection(1),
      models: collection(1),
      processes: collection(1),
      findings: collection(2),
      activityRollups: collection(2),
      incidentHistory: collection(2),
    },
    host: {
      hostname: "studio",
      platform: "darwin",
      arch: "arm64",
      uptimeMs: 10_000,
      logicalCpuCount: 12,
      loadAverage: [1, 2, 3],
      totalMemoryBytes: 64 * 1024 ** 3,
      freeMemoryBytes: 32 * 1024 ** 3,
      availableMemoryBytes: 36 * 1024 ** 3,
      usedMemoryBytes: 28 * 1024 ** 3,
      memoryUsedPercent: 43.8,
      memoryAvailabilitySource: "macos_memory_pressure",
      localModelProcessCount: 2,
      localModelRssBytes: 24 * 1024 ** 3,
      processRssBytes: 256 * 1024 ** 2,
      processHeapUsedBytes: 64 * 1024 ** 2,
      processHeapTotalBytes: 128 * 1024 ** 2,
      eventLoopLagMs: 4,
      status: "healthy",
    },
    agents: [
      {
        id: "main",
        name: "Control Director",
        workspace: "/workspace",
        duty: "always_on",
        dutySource: "heartbeat",
        status: "working",
        activityState: "working",
        healthState: "healthy",
        attentionState: "none",
        model: "ollama/gemma",
        fallbackModels: ["ollama/qwen"],
        activeTaskCount: 1,
        blockedTaskCount: 0,
        latestTask: OPERATIONS_RAW_PROMPT_SENTINEL,
        latestActivityAt: now - 5_000,
        currentWork: {
          taskId: "task-1",
          title: "Verify Operations Room",
          summary: "Checking the compact status and navigation experience.",
          updatedAt: now - 5_000,
          outcome: "active",
        },
        lastActivity: {
          taskId: "task-0",
          title: "Prepared the UI proof",
          updatedAt: now - 60_000,
          outcome: "succeeded",
        },
        heartbeat: { enabled: true, every: "30m", everyMs: 1_800_000, target: "last" },
        memoryBytes: null,
        memoryAttribution: "unavailable",
      },
      {
        id: "release-ops",
        name: "Release Ops",
        workspace: "/workspace",
        duty: "on_demand",
        dutySource: "configuration",
        status: "degraded",
        activityState: "waiting",
        healthState: "degraded",
        attentionState: "handling",
        model: "ollama/qwen",
        fallbackModels: [],
        activeTaskCount: 0,
        blockedTaskCount: 0,
        latestActivityAt: now - 20_000,
        heartbeat: { enabled: false, every: "off", everyMs: null, target: "last" },
        memoryBytes: null,
        memoryAttribution: "unavailable",
      },
      {
        id: "ready-agent",
        name: "Ready Agent",
        workspace: "/workspace",
        duty: "on_demand",
        dutySource: "configuration",
        status: "idle",
        activityState: "ready",
        healthState: "healthy",
        attentionState: "none",
        fallbackModels: [],
        activeTaskCount: 0,
        blockedTaskCount: 0,
        currentWork: {
          taskId: "finished-task",
          title: "Old completed work",
          updatedAt: now - 120_000,
          outcome: "succeeded",
        },
        latestActivityAt: now - 120_000,
        heartbeat: { enabled: false, every: "off", everyMs: null, target: "last" },
        memoryBytes: null,
        memoryAttribution: "unavailable",
      },
      {
        id: "off-agent",
        name: "Off Agent",
        workspace: "/workspace",
        duty: "disabled",
        dutySource: "configuration",
        status: "disabled",
        activityState: "off",
        healthState: "unknown",
        attentionState: "none",
        fallbackModels: [],
        activeTaskCount: 0,
        blockedTaskCount: 0,
        heartbeat: { enabled: false, every: "off", everyMs: null, target: "last" },
        memoryBytes: null,
        memoryAttribution: "unavailable",
      },
    ],
    tasks: [
      {
        id: "task-1",
        title: OPERATIONS_RAW_PROMPT_SENTINEL,
        runtime: "subagent",
        agentId: "main",
        parentFlowId: "flow-1",
        status: "working",
        sourceStatus: "running",
        progress: OPERATIONS_RAW_PROMPT_SENTINEL,
        updatedAt: now - 5_000,
      },
      {
        id: "task-2",
        title: OPERATIONS_RAW_PROMPT_SENTINEL,
        runtime: "cli",
        status: "healthy",
        sourceStatus: "completed",
        updatedAt: now - 30_000,
      },
    ],
    workflows: [
      {
        id: "flow-1",
        title: "Managed verification workflow",
        ownerKey: "agent:main:main",
        status: "working",
        sourceStatus: "running",
        currentStep: "Reviewing runtime truth",
        hasWaitState: false,
        activeTaskCount: 1,
        failedTaskCount: 0,
        updatedAt: now - 5_000,
      },
    ],
    cronJobs: [
      {
        id: "cron-1",
        name: "Health sweep",
        duty: "scheduled",
        status: "healthy",
        enabled: true,
        running: false,
        nextRunAt: now + 60_000,
        consecutiveErrors: 0,
      },
    ],
    skills: [
      {
        id: "testing",
        name: "Testing",
        kind: "skill",
        status: "healthy",
        configured: true,
        active: true,
        availability: "available",
      },
    ],
    plugins: [
      {
        id: "apps",
        name: "Apps",
        kind: "plugin",
        status: "healthy",
        configured: true,
        active: true,
        availability: "available",
      },
    ],
    tools: [
      {
        id: "exec",
        name: "Exec",
        kind: "tool",
        status: "healthy",
        configured: true,
        active: true,
        availability: "available",
      },
    ],
    models: [
      {
        id: "ollama/gemma",
        name: "Gemma",
        kind: "model",
        status: "healthy",
        configured: true,
        active: null,
        route: "local",
        availability: "available",
      },
    ],
    processes: [
      {
        pid: 42,
        parentPid: 1,
        command: "node",
        rssBytes: 128 * 1024 ** 2,
        cpuPercent: 1.5,
        kind: "gateway",
      },
    ],
    findings: [
      {
        id: "skill:requirements:blocked",
        severity: "warning",
        category: "skill",
        title: "One skill needs setup",
        detail: OPERATIONS_RAW_PROMPT_SENTINEL,
        firstObservedAt: now - 60_000,
        lastObservedAt: now,
        disposition: "handling",
        responseState: "in_progress",
        impact: "One optional capability is unavailable.",
        ownerId: "release-ops",
        nextAction: "Install the required local tool.",
      },
      {
        id: "workflow:historical",
        severity: "warning",
        category: "workflow",
        title: "Old workflow issue",
        detail: OPERATIONS_RAW_PROMPT_SENTINEL,
        firstObservedAt: now - 3_600_000,
        lastObservedAt: now - 3_000_000,
        resolvedAt: now - 2_900_000,
        disposition: "historical",
        responseState: "resolved",
        impact: "No current impact.",
      },
    ],
    activityRollups: [
      {
        key: "subagent:task-1:working",
        runtime: "subagent",
        sourceId: "task-1",
        taskId: "task-1",
        title: "Verify Operations Room",
        count: 1,
        latestAt: now - 5_000,
        status: "working",
        agentId: "main",
      },
      {
        key: "cli:task-2:succeeded",
        runtime: "cli",
        sourceId: "task-2",
        title: "Static UI inspection",
        count: 1,
        latestAt: now - 30_000,
        status: "succeeded",
      },
    ],
    incidentHistory: [
      {
        id: "skill:requirements:blocked",
        title: "One skill needs setup",
        category: "skill",
        severity: "warning",
        disposition: "handling",
        responseState: "in_progress",
        firstObservedAt: now - 60_000,
        lastObservedAt: now,
        transitions: [{ at: now - 60_000, to: "warning" }],
      },
      {
        id: "workflow:historical",
        title: "Old workflow issue",
        category: "workflow",
        severity: "warning",
        disposition: "historical",
        responseState: "resolved",
        firstObservedAt: now - 3_600_000,
        lastObservedAt: now - 3_000_000,
        resolvedAt: now - 2_900_000,
        transitions: [{ at: now - 3_600_000, to: "warning" }],
      },
    ],
    incidentLedger: { overflowCount: 0 },
    reconciler: {
      mode: "shadow",
      autoRemediationEnabled: false,
      intervalMs: 60_000,
      lastAttemptAt: now,
      lastSweepAt: now,
      nextSweepAt: now + 60_000,
      attemptCount: 1,
      sweepCount: 1,
      recommendedActionCount: 1,
      ruleCount: 10,
      note: "Deterministic shadow monitor active.",
    },
    controls: {
      mode: "guarded",
      previewRequired: true,
      supportedActions: [
        "cron.run",
        "cron.enable",
        "cron.disable",
        "remediation.investigate",
        "task.cancel",
        "flow.cancel",
      ],
      note: "Confirmation required.",
    },
  };
}

export function createSevenGroupOperationsTestSnapshot(now = Date.now()): OperationsSnapshot {
  const snapshot = createOperationsTestSnapshot(now);
  const ready = snapshot.agents.find((agent) => agent.id === "ready-agent")!;
  const off = snapshot.agents.find((agent) => agent.id === "off-agent")!;
  const readyWithoutWork = { ...ready };
  delete readyWithoutWork.currentWork;
  delete readyWithoutWork.lastActivity;
  snapshot.agents = [
    {
      ...off,
      id: "urgent-agent",
      name: "Urgent Agent",
      duty: "on_demand",
      status: "failed",
      activityState: "waiting",
      healthState: "failed",
      attentionState: "urgent",
      latestActivityAt: now - 2_000,
    },
    snapshot.agents.find((agent) => agent.id === "release-ops")!,
    snapshot.agents.find((agent) => agent.id === "main")!,
    {
      ...readyWithoutWork,
      id: "scheduled-agent",
      name: "Scheduled Agent",
      duty: "scheduled",
      dutySource: "schedule",
      status: "idle",
      activityState: "scheduled",
      latestActivityAt: now - 90_000,
    },
    {
      ...readyWithoutWork,
      id: "recent-agent",
      name: "Recently Changed Agent",
      lastActivity: {
        taskId: "recent-task",
        title: "Completed a recent check",
        updatedAt: now - 5_000,
        outcome: "succeeded",
      },
      latestActivityAt: now - 5_000,
    },
    ready,
    off,
  ];
  snapshot.summary.agents = snapshot.agents.length;
  snapshot.summary.attentionAgents = 2;
  snapshot.collections.agents = collection(snapshot.agents.length);
  return snapshot;
}
