/**
 * Central registry for every gateway protocol schema.
 *
 * The keys in this object are the public schema names used by validators,
 * generated static types, and protocol tooling. Add new entries here only after
 * the owning schema module exports the canonical TypeBox schema.
 */
import type { TSchema } from "typebox";
import {
  AgentEventSchema,
  AgentIdentityParamsSchema,
  AgentIdentityResultSchema,
  AgentParamsSchema,
  AgentWaitParamsSchema,
  MessageActionParamsSchema,
  PollParamsSchema,
  SendParamsSchema,
  WakeParamsSchema,
} from "./agent.js";
import {
  AgentSummarySchema,
  AgentsCreateParamsSchema,
  AgentsCreateResultSchema,
  AgentsDeleteParamsSchema,
  AgentsDeleteResultSchema,
  AgentsFileEntrySchema,
  AgentsFilesGetParamsSchema,
  AgentsFilesGetResultSchema,
  AgentsFilesListParamsSchema,
  AgentsFilesListResultSchema,
  AgentsFilesSetParamsSchema,
  AgentsFilesSetResultSchema,
  AgentsListParamsSchema,
  AgentsListResultSchema,
  AgentsUpdateParamsSchema,
  AgentsUpdateResultSchema,
  ModelChoiceSchema,
  ModelsListParamsSchema,
  ModelsListResultSchema,
  SkillsBinsParamsSchema,
  SkillsBinsResultSchema,
  SkillsDetailParamsSchema,
  SkillsDetailResultSchema,
  SkillsInstallParamsSchema,
  SkillsProposalActionParamsSchema,
  SkillsProposalApplyResultSchema,
  SkillsProposalCreateParamsSchema,
  SkillsProposalInspectParamsSchema,
  SkillsProposalInspectResultSchema,
  SkillsProposalRecordResultSchema,
  SkillsProposalRequestRevisionParamsSchema,
  SkillsProposalRequestRevisionResultSchema,
  SkillsProposalReviseParamsSchema,
  SkillsProposalUpdateParamsSchema,
  SkillsProposalsListParamsSchema,
  SkillsProposalsListResultSchema,
  SkillsSearchParamsSchema,
  SkillsSearchResultSchema,
  SkillsSecurityVerdictsParamsSchema,
  SkillsSecurityVerdictsResultSchema,
  SkillsSkillCardParamsSchema,
  SkillsSkillCardResultSchema,
  SkillsStatusParamsSchema,
  SkillsUploadBeginParamsSchema,
  SkillsUploadChunkParamsSchema,
  SkillsUploadCommitParamsSchema,
  SkillsUpdateParamsSchema,
  ToolCatalogEntrySchema,
  ToolCatalogGroupSchema,
  ToolCatalogProfileSchema,
  ToolsCatalogParamsSchema,
  ToolsCatalogResultSchema,
  ToolsEffectiveEntrySchema,
  ToolsEffectiveGroupSchema,
  ToolsEffectiveNoticeSchema,
  ToolsEffectiveParamsSchema,
  ToolsEffectiveResultSchema,
  ToolsInvokeErrorSchema,
  ToolsInvokeParamsSchema,
  ToolsInvokeResultSchema,
} from "./agents-models-skills.js";
import {
  ArtifactSummarySchema,
  ArtifactsDownloadParamsSchema,
  ArtifactsDownloadResultSchema,
  ArtifactsGetParamsSchema,
  ArtifactsGetResultSchema,
  ArtifactsListParamsSchema,
  ArtifactsListResultSchema,
} from "./artifacts.js";
import {
  ChannelsStartParamsSchema,
  ChannelsStopParamsSchema,
  ChannelsLogoutParamsSchema,
  TalkEventSchema,
  TalkCatalogParamsSchema,
  TalkCatalogResultSchema,
  TalkClientCreateParamsSchema,
  TalkClientCreateResultSchema,
  TalkAgentControlResultSchema,
  TalkClientSteerParamsSchema,
  TalkClientToolCallParamsSchema,
  TalkClientToolCallResultSchema,
  TalkConfigParamsSchema,
  TalkConfigResultSchema,
  TalkSessionAppendAudioParamsSchema,
  TalkSessionCancelOutputParamsSchema,
  TalkSessionCancelTurnParamsSchema,
  TalkSessionCloseParamsSchema,
  TalkSessionCreateParamsSchema,
  TalkSessionCreateResultSchema,
  TalkSessionJoinParamsSchema,
  TalkSessionJoinResultSchema,
  TalkSessionOkResultSchema,
  TalkSessionSteerParamsSchema,
  TalkSessionSubmitToolResultParamsSchema,
  TalkSessionTurnResultSchema,
  TalkSessionTurnParamsSchema,
  TalkSpeakParamsSchema,
  TalkSpeakResultSchema,
  ChannelsStatusParamsSchema,
  ChannelsStatusResultSchema,
  TalkModeParamsSchema,
  WebLoginStartParamsSchema,
  WebLoginWaitParamsSchema,
} from "./channels.js";
import {
  CommandEntrySchema,
  CommandsListParamsSchema,
  CommandsListResultSchema,
} from "./commands.js";
import {
  ConfigApplyParamsSchema,
  ConfigGetParamsSchema,
  ConfigPatchParamsSchema,
  ConfigSchemaLookupParamsSchema,
  ConfigSchemaLookupResultSchema,
  ConfigSchemaParamsSchema,
  ConfigSchemaResponseSchema,
  ConfigSetParamsSchema,
  UpdateStatusParamsSchema,
  UpdateRunParamsSchema,
} from "./config.js";
import {
  CronAddParamsSchema,
  CronGetParamsSchema,
  CronJobSchema,
  CronListParamsSchema,
  CronRemoveParamsSchema,
  CronRunLogEntrySchema,
  CronRunParamsSchema,
  CronRunsParamsSchema,
  CronStatusParamsSchema,
  CronUpdateParamsSchema,
} from "./cron.js";
import {
  DevicePairApproveParamsSchema,
  DevicePairListParamsSchema,
  DevicePairRemoveParamsSchema,
  DevicePairRejectParamsSchema,
  DevicePairRequestedEventSchema,
  DevicePairResolvedEventSchema,
  DeviceTokenRevokeParamsSchema,
  DeviceTokenRotateParamsSchema,
} from "./devices.js";
import {
  EnvironmentSummarySchema,
  EnvironmentsListParamsSchema,
  EnvironmentsListResultSchema,
  EnvironmentsStatusParamsSchema,
  EnvironmentsStatusResultSchema,
  EnvironmentStatusSchema,
} from "./environments.js";
import {
  ExecApprovalsGetParamsSchema,
  ExecApprovalsNodeGetParamsSchema,
  ExecApprovalsNodeSetParamsSchema,
  ExecApprovalsSetParamsSchema,
  ExecApprovalsSnapshotSchema,
  ExecApprovalGetParamsSchema,
  ExecApprovalRequestParamsSchema,
  ExecApprovalResolveParamsSchema,
} from "./exec-approvals.js";
import {
  ConnectParamsSchema,
  ErrorShapeSchema,
  EventFrameSchema,
  GatewayFrameSchema,
  HelloOkSchema,
  RequestFrameSchema,
  ResponseFrameSchema,
  ShutdownEventSchema,
  TickEventSchema,
} from "./frames.js";
import {
  ChatAbortedEventSchema,
  ChatAbortParamsSchema,
  ChatDeltaEventSchema,
  ChatErrorEventSchema,
  ChatEventSchema,
  ChatFinalEventSchema,
  ChatHistoryParamsSchema,
  ChatMetadataParamsSchema,
  ChatMessageGetParamsSchema,
  ChatMessageGetResultSchema,
  ChatInjectParamsSchema,
  ChatSendParamsSchema,
  LogsTailParamsSchema,
  LogsTailResultSchema,
} from "./logs-chat.js";
import {
  NodeDescribeParamsSchema,
  NodeEventParamsSchema,
  NodeEventResultSchema,
  NodePendingDrainParamsSchema,
  NodePendingDrainResultSchema,
  NodePendingEnqueueParamsSchema,
  NodePendingEnqueueResultSchema,
  NodePresenceAlivePayloadSchema,
  NodePresenceAliveReasonSchema,
  NodeInvokeParamsSchema,
  NodeInvokeResultParamsSchema,
  NodeInvokeRequestEventSchema,
  NodeListParamsSchema,
  NodePendingAckParamsSchema,
  NodePairApproveParamsSchema,
  NodePairListParamsSchema,
  NodePairRemoveParamsSchema,
  NodePairRejectParamsSchema,
  NodePairRequestParamsSchema,
  NodePairVerifyParamsSchema,
  NodeRenameParamsSchema,
} from "./nodes.js";
import {
  PccCompletionReceiptSchema,
  PccDecisionSchema,
  PccDecisionsAddParamsSchema,
  PccDecisionsAddResultSchema,
  PccEvidenceAddParamsSchema,
  PccEvidenceAddResultSchema,
  PccEvidenceKindSchema,
  PccEvidenceSchema,
  PccEvidenceStatusSchema,
  PccLastKnownGoodSchema,
  PccLastKnownGoodUpsertParamsSchema,
  PccLastKnownGoodUpsertResultSchema,
  PccMilestoneSchema,
  PccSubMilestoneSchema,
  PccMilestonesUpsertParamsSchema,
  PccSubMilestonesListParamsSchema,
  PccSubMilestonesListResultSchema,
  PccSubMilestonesUpsertParamsSchema,
  PccSubMilestonesUpsertResultSchema,
  PccMilestonesUpsertResultSchema,
  PccPermissionGrantSchema,
  PccPermissionStatusSchema,
  PccPermissionTypeSchema,
  PccPermissionsUpsertParamsSchema,
  PccPermissionsUpsertResultSchema,
  PccPhaseSchema,
  PccPortfolioSummarySchema,
  PccProjectSchema,
  PccProjectSummarySchema,
  PccProjectsGetParamsSchema,
  PccProjectsGetResultSchema,
  PccProjectsListParamsSchema,
  PccProjectsListResultSchema,
  PccProjectsUpsertParamsSchema,
  PccProjectsUpsertResultSchema,
  PccProofLevelSchema,
  PccReceiptsAddParamsSchema,
  PccReceiptsAddResultSchema,
  PccRiskLevelSchema,
  PccStatusSchema,
  PccSummaryGetParamsSchema,
  PccSummaryGetResultSchema,
} from "./pcc.js";
import {
  PluginApprovalRequestParamsSchema,
  PluginApprovalResolveParamsSchema,
} from "./plugin-approvals.js";
import {
  PluginControlUiDescriptorSchema,
  PluginsSessionActionFailureResultSchema,
  PluginsSessionActionParamsSchema,
  PluginsSessionActionResultSchema,
  PluginsSessionActionSuccessResultSchema,
  PluginsUiDescriptorsParamsSchema,
  PluginsUiDescriptorsResultSchema,
} from "./plugins.js";
import { PushTestParamsSchema, PushTestResultSchema } from "./push.js";
import {
  SecretsReloadParamsSchema,
  SecretsResolveAssignmentSchema,
  SecretsResolveParamsSchema,
  SecretsResolveResultSchema,
} from "./secrets.js";
import * as SelfImprovementProtocol from "./self-improvement.js";
import {
  SessionsAbortParamsSchema,
  SessionsCompactParamsSchema,
  SessionsCompactionBranchParamsSchema,
  SessionsCompactionBranchResultSchema,
  SessionsCompactionGetParamsSchema,
  SessionsCompactionGetResultSchema,
  SessionsCompactionListParamsSchema,
  SessionsCompactionListResultSchema,
  SessionsCompactionRestoreParamsSchema,
  SessionsCompactionRestoreResultSchema,
  SessionFileBrowserEntrySchema,
  SessionFileBrowserResultSchema,
  SessionCompactionCheckpointSchema,
  SessionFileEntrySchema,
  SessionFileKindSchema,
  SessionFileRelevanceSchema,
  SessionOperationEventSchema,
  SessionsCleanupParamsSchema,
  SessionsCreateParamsSchema,
  SessionsDeleteParamsSchema,
  SessionsDescribeParamsSchema,
  SessionsFilesGetParamsSchema,
  SessionsFilesGetResultSchema,
  SessionsFilesListParamsSchema,
  SessionsFilesListResultSchema,
  SessionsListParamsSchema,
  SessionsMessagesSubscribeParamsSchema,
  SessionsMessagesUnsubscribeParamsSchema,
  SessionsPatchParamsSchema,
  SessionsPluginPatchParamsSchema,
  SessionsPluginPatchResultSchema,
  SessionsPreviewParamsSchema,
  SessionsResetParamsSchema,
  SessionsResolveParamsSchema,
  SessionsSendParamsSchema,
  SessionsUsageParamsSchema,
} from "./sessions.js";
import { PresenceEntrySchema, SnapshotSchema, StateVersionSchema } from "./snapshot.js";
import {
  TaskFlowDetailSchema,
  TaskFlowsCancelParamsSchema,
  TaskFlowsCancelResultSchema,
  TaskFlowsCreateParamsSchema,
  TaskFlowsCreateResultSchema,
  TaskFlowsGetParamsSchema,
  TaskFlowsGetResultSchema,
  TaskFlowsListParamsSchema,
  TaskFlowsListResultSchema,
  TaskFlowStatusSchema,
  TaskFlowSummarySchema,
  TasksCancelParamsSchema,
  TasksCancelResultSchema,
  TasksGetParamsSchema,
  TasksGetResultSchema,
  TasksListParamsSchema,
  TasksListResultSchema,
  TaskSummarySchema,
} from "./tasks.js";
import {
  WizardCancelParamsSchema,
  WizardNextParamsSchema,
  WizardNextResultSchema,
  WizardStartParamsSchema,
  WizardStartResultSchema,
  WizardStatusParamsSchema,
  WizardStatusResultSchema,
  WizardStepSchema,
} from "./wizard.js";

function asPublicSchema(schema: TSchema): TSchema {
  return schema;
}

/** Public schema registry keyed by stable protocol schema name. */
export const ProtocolSchemas = {
  // Keep SIG's exact runtime validators while preventing their large TypeBox
  // implementation types from expanding the public plugin-SDK declaration graph.
  SelfImprovementRecommendation: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementRecommendationSchema,
  ),
  SelfImprovementProposal: asPublicSchema(SelfImprovementProtocol.SelfImprovementProposalSchema),
  SelfImprovementDailyScorecard: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementDailyScorecardSchema,
  ),
  SelfImprovementAuditEvent: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementAuditEventSchema,
  ),
  SelfImprovementScanSummary: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementScanSummarySchema,
  ),
  SelfImprovementScanParams: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementScanParamsSchema,
  ),
  SelfImprovementScanResult: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementScanResultSchema,
  ),
  SelfImprovementScorecardParams: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementScorecardParamsSchema,
  ),
  SelfImprovementScorecardResult: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementScorecardResultSchema,
  ),
  SelfImprovementHealthParams: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementHealthParamsSchema,
  ),
  SelfImprovementProductionCheckParams: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementProductionCheckParamsSchema,
  ),
  SelfImprovementProductionCheckResult: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementProductionCheckResultSchema,
  ),
  SelfImprovementMaintenanceRunParams: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementMaintenanceRunParamsSchema,
  ),
  SelfImprovementMaintenanceResult: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementMaintenanceResultSchema,
  ),
  SelfImprovementDashboardInterventionParams: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementDashboardInterventionParamsSchema,
  ),
  SelfImprovementDashboardInterventionResult: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementDashboardInterventionResultSchema,
  ),
  SelfImprovementProofReceipt: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementProofReceiptSchema,
  ),
  SelfImprovementProofReceiptsListParams: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementProofReceiptsListParamsSchema,
  ),
  SelfImprovementProofReceiptsListResult: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementProofReceiptsListResultSchema,
  ),
  SelfImprovementProofReceiptRecordParams: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementProofReceiptRecordParamsSchema,
  ),
  SelfImprovementProofReceiptRecordResult: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementProofReceiptRecordResultSchema,
  ),
  SelfImprovementOperationalHealthResult: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementOperationalHealthResultSchema,
  ),
  SelfImprovementAnalysisRunParams: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementAnalysisRunParamsSchema,
  ),
  SelfImprovementAnalysisRunResult: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementAnalysisRunResultSchema,
  ),
  SelfImprovementAuditEventsListParams: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementAuditEventsListParamsSchema,
  ),
  SelfImprovementAuditEventsListResult: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementAuditEventsListResultSchema,
  ),
  SelfImprovementModelPreflightParams: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementModelPreflightParamsSchema,
  ),
  SelfImprovementModelPreflightResult: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementModelPreflightResultSchema,
  ),
  SelfImprovementReviewerEvalRunParams: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementReviewerEvalRunParamsSchema,
  ),
  SelfImprovementReviewerEvalRunResult: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementReviewerEvalRunResultSchema,
  ),
  SelfImprovementGroupsUpdateParams: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementGroupsUpdateParamsSchema,
  ),
  SelfImprovementGroupsUpdateResult: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementGroupsUpdateResultSchema,
  ),
  SelfImprovementRecommendationsListParams: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementRecommendationsListParamsSchema,
  ),
  SelfImprovementRecommendationsListResult: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementRecommendationsListResultSchema,
  ),
  SelfImprovementRecommendationsSummaryParams: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementRecommendationsSummaryParamsSchema,
  ),
  SelfImprovementRecommendationsSummaryResult: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementRecommendationsSummaryResultSchema,
  ),
  SelfImprovementRecommendationsGetParams: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementRecommendationsGetParamsSchema,
  ),
  SelfImprovementRecommendationsGetResult: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementRecommendationsGetResultSchema,
  ),
  SelfImprovementRecommendationsUpdateParams: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementRecommendationsUpdateParamsSchema,
  ),
  SelfImprovementRecommendationsUpdateResult: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementRecommendationsUpdateResultSchema,
  ),
  SelfImprovementProposalsListParams: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementProposalsListParamsSchema,
  ),
  SelfImprovementProposalsListResult: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementProposalsListResultSchema,
  ),
  SelfImprovementProposalsGetParams: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementProposalsGetParamsSchema,
  ),
  SelfImprovementProposalsGetResult: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementProposalsGetResultSchema,
  ),
  SelfImprovementProposalsUpdateParams: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementProposalsUpdateParamsSchema,
  ),
  SelfImprovementProposalsUpdateResult: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementProposalsUpdateResultSchema,
  ),
  SelfImprovementCuratorListParams: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementCuratorListParamsSchema,
  ),
  SelfImprovementCuratorListResult: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementCuratorListResultSchema,
  ),
  SelfImprovementCuratorGetParams: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementCuratorGetParamsSchema,
  ),
  SelfImprovementCuratorGetResult: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementCuratorGetResultSchema,
  ),
  SelfImprovementCuratorUpdateParams: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementCuratorUpdateParamsSchema,
  ),
  SelfImprovementCuratorUpdateResult: asPublicSchema(
    SelfImprovementProtocol.SelfImprovementCuratorUpdateResultSchema,
  ),
  // Handshake, transport frames, state snapshots, and shared error envelopes.
  ConnectParams: ConnectParamsSchema,
  HelloOk: HelloOkSchema,
  RequestFrame: RequestFrameSchema,
  ResponseFrame: ResponseFrameSchema,
  EventFrame: EventFrameSchema,
  GatewayFrame: GatewayFrameSchema,
  PresenceEntry: PresenceEntrySchema,
  StateVersion: StateVersionSchema,
  Snapshot: SnapshotSchema,
  ErrorShape: ErrorShapeSchema,

  // Environment and agent-facing control RPC payloads.
  EnvironmentStatus: EnvironmentStatusSchema,
  EnvironmentSummary: EnvironmentSummarySchema,
  EnvironmentsListParams: EnvironmentsListParamsSchema,
  EnvironmentsListResult: EnvironmentsListResultSchema,
  EnvironmentsStatusParams: EnvironmentsStatusParamsSchema,
  EnvironmentsStatusResult: EnvironmentsStatusResultSchema,
  AgentEvent: AgentEventSchema,
  MessageActionParams: MessageActionParamsSchema,
  SendParams: SendParamsSchema,
  PollParams: PollParamsSchema,
  AgentParams: AgentParamsSchema,
  AgentIdentityParams: AgentIdentityParamsSchema,
  AgentIdentityResult: AgentIdentityResultSchema,
  AgentWaitParams: AgentWaitParamsSchema,
  WakeParams: WakeParamsSchema,

  // Node pairing, invocation, presence, and pending-queue payloads.
  NodePairRequestParams: NodePairRequestParamsSchema,
  NodePairListParams: NodePairListParamsSchema,
  NodePairApproveParams: NodePairApproveParamsSchema,
  NodePairRejectParams: NodePairRejectParamsSchema,
  NodePairRemoveParams: NodePairRemoveParamsSchema,
  NodePairVerifyParams: NodePairVerifyParamsSchema,
  NodeRenameParams: NodeRenameParamsSchema,
  NodeListParams: NodeListParamsSchema,
  NodePendingAckParams: NodePendingAckParamsSchema,
  NodeDescribeParams: NodeDescribeParamsSchema,
  NodeInvokeParams: NodeInvokeParamsSchema,
  NodeInvokeResultParams: NodeInvokeResultParamsSchema,
  NodeEventParams: NodeEventParamsSchema,
  NodeEventResult: NodeEventResultSchema,
  NodePresenceAlivePayload: NodePresenceAlivePayloadSchema,
  NodePresenceAliveReason: NodePresenceAliveReasonSchema,
  NodePendingDrainParams: NodePendingDrainParamsSchema,
  NodePendingDrainResult: NodePendingDrainResultSchema,
  NodePendingEnqueueParams: NodePendingEnqueueParamsSchema,
  NodePendingEnqueueResult: NodePendingEnqueueResultSchema,
  NodeInvokeRequestEvent: NodeInvokeRequestEventSchema,

  // Push and secret-resolution payloads used by mobile/control integrations.
  PushTestParams: PushTestParamsSchema,
  PushTestResult: PushTestResultSchema,
  SecretsReloadParams: SecretsReloadParamsSchema,
  SecretsResolveParams: SecretsResolveParamsSchema,
  SecretsResolveAssignment: SecretsResolveAssignmentSchema,
  SecretsResolveResult: SecretsResolveResultSchema,

  // Session lifecycle, message routing, compaction, and usage accounting.
  SessionsListParams: SessionsListParamsSchema,
  SessionsCleanupParams: SessionsCleanupParamsSchema,
  SessionsPreviewParams: SessionsPreviewParamsSchema,
  SessionsDescribeParams: SessionsDescribeParamsSchema,
  SessionsResolveParams: SessionsResolveParamsSchema,
  SessionCompactionCheckpoint: SessionCompactionCheckpointSchema,
  SessionOperationEvent: SessionOperationEventSchema,
  SessionsCompactionListParams: SessionsCompactionListParamsSchema,
  SessionsCompactionGetParams: SessionsCompactionGetParamsSchema,
  SessionsCompactionBranchParams: SessionsCompactionBranchParamsSchema,
  SessionsCompactionRestoreParams: SessionsCompactionRestoreParamsSchema,
  SessionsCompactionListResult: SessionsCompactionListResultSchema,
  SessionsCompactionGetResult: SessionsCompactionGetResultSchema,
  SessionsCompactionBranchResult: SessionsCompactionBranchResultSchema,
  SessionsCompactionRestoreResult: SessionsCompactionRestoreResultSchema,
  SessionFileBrowserEntry: SessionFileBrowserEntrySchema,
  SessionFileBrowserResult: SessionFileBrowserResultSchema,
  SessionFileKind: SessionFileKindSchema,
  SessionFileEntry: SessionFileEntrySchema,
  SessionFileRelevance: SessionFileRelevanceSchema,
  SessionsFilesListParams: SessionsFilesListParamsSchema,
  SessionsFilesListResult: SessionsFilesListResultSchema,
  SessionsFilesGetParams: SessionsFilesGetParamsSchema,
  SessionsFilesGetResult: SessionsFilesGetResultSchema,
  SessionsCreateParams: SessionsCreateParamsSchema,
  SessionsSendParams: SessionsSendParamsSchema,
  SessionsMessagesSubscribeParams: SessionsMessagesSubscribeParamsSchema,
  SessionsMessagesUnsubscribeParams: SessionsMessagesUnsubscribeParamsSchema,
  SessionsAbortParams: SessionsAbortParamsSchema,
  SessionsPatchParams: SessionsPatchParamsSchema,
  SessionsPluginPatchParams: SessionsPluginPatchParamsSchema,
  SessionsPluginPatchResult: SessionsPluginPatchResultSchema,
  SessionsResetParams: SessionsResetParamsSchema,
  SessionsDeleteParams: SessionsDeleteParamsSchema,
  SessionsCompactParams: SessionsCompactParamsSchema,
  SessionsUsageParams: SessionsUsageParamsSchema,

  // Task ledger and config/wizard setup payloads.
  TaskFlowStatus: TaskFlowStatusSchema,
  TaskFlowSummary: TaskFlowSummarySchema,
  TaskFlowDetail: TaskFlowDetailSchema,
  TaskFlowsListParams: TaskFlowsListParamsSchema,
  TaskFlowsListResult: TaskFlowsListResultSchema,
  TaskFlowsGetParams: TaskFlowsGetParamsSchema,
  TaskFlowsGetResult: TaskFlowsGetResultSchema,
  TaskFlowsCreateParams: TaskFlowsCreateParamsSchema,
  TaskFlowsCreateResult: TaskFlowsCreateResultSchema,
  TaskFlowsCancelParams: TaskFlowsCancelParamsSchema,
  TaskFlowsCancelResult: TaskFlowsCancelResultSchema,
  TaskSummary: TaskSummarySchema,
  TasksListParams: TasksListParamsSchema,
  TasksListResult: TasksListResultSchema,
  TasksGetParams: TasksGetParamsSchema,
  TasksGetResult: TasksGetResultSchema,
  TasksCancelParams: TasksCancelParamsSchema,
  TasksCancelResult: TasksCancelResultSchema,

  // Project Command Center project, milestone, permission, evidence, and receipt payloads.
  PccStatus: PccStatusSchema,
  PccProofLevel: PccProofLevelSchema,
  PccPermissionStatus: PccPermissionStatusSchema,
  PccPermissionType: PccPermissionTypeSchema,
  PccRiskLevel: PccRiskLevelSchema,
  PccEvidenceKind: PccEvidenceKindSchema,
  PccEvidenceStatus: PccEvidenceStatusSchema,
  PccPhase: PccPhaseSchema,
  PccProject: PccProjectSchema,
  PccMilestone: PccMilestoneSchema,
  PccSubMilestone: PccSubMilestoneSchema,
  PccPermissionGrant: PccPermissionGrantSchema,
  PccEvidence: PccEvidenceSchema,
  PccCompletionReceipt: PccCompletionReceiptSchema,
  PccDecision: PccDecisionSchema,
  PccDecisionsAddParams: PccDecisionsAddParamsSchema,
  PccDecisionsAddResult: PccDecisionsAddResultSchema,
  PccLastKnownGood: PccLastKnownGoodSchema,
  PccLastKnownGoodUpsertParams: PccLastKnownGoodUpsertParamsSchema,
  PccLastKnownGoodUpsertResult: PccLastKnownGoodUpsertResultSchema,
  PccProjectSummary: PccProjectSummarySchema,
  PccPortfolioSummary: PccPortfolioSummarySchema,
  PccProjectsListParams: PccProjectsListParamsSchema,
  PccProjectsListResult: PccProjectsListResultSchema,
  PccProjectsGetParams: PccProjectsGetParamsSchema,
  PccProjectsGetResult: PccProjectsGetResultSchema,
  PccProjectsUpsertParams: PccProjectsUpsertParamsSchema,
  PccProjectsUpsertResult: PccProjectsUpsertResultSchema,
  PccMilestonesUpsertParams: PccMilestonesUpsertParamsSchema,
  PccMilestonesUpsertResult: PccMilestonesUpsertResultSchema,
  PccSubMilestonesListParams: PccSubMilestonesListParamsSchema,
  PccSubMilestonesListResult: PccSubMilestonesListResultSchema,
  PccSubMilestonesUpsertParams: PccSubMilestonesUpsertParamsSchema,
  PccSubMilestonesUpsertResult: PccSubMilestonesUpsertResultSchema,
  PccPermissionsUpsertParams: PccPermissionsUpsertParamsSchema,
  PccPermissionsUpsertResult: PccPermissionsUpsertResultSchema,
  PccEvidenceAddParams: PccEvidenceAddParamsSchema,
  PccEvidenceAddResult: PccEvidenceAddResultSchema,
  PccReceiptsAddParams: PccReceiptsAddParamsSchema,
  PccReceiptsAddResult: PccReceiptsAddResultSchema,
  PccSummaryGetParams: PccSummaryGetParamsSchema,
  PccSummaryGetResult: PccSummaryGetResultSchema,
  ConfigGetParams: ConfigGetParamsSchema,
  ConfigSetParams: ConfigSetParamsSchema,
  ConfigApplyParams: ConfigApplyParamsSchema,
  ConfigPatchParams: ConfigPatchParamsSchema,
  ConfigSchemaParams: ConfigSchemaParamsSchema,
  ConfigSchemaLookupParams: ConfigSchemaLookupParamsSchema,
  ConfigSchemaResponse: ConfigSchemaResponseSchema,
  ConfigSchemaLookupResult: ConfigSchemaLookupResultSchema,
  WizardStartParams: WizardStartParamsSchema,
  WizardNextParams: WizardNextParamsSchema,
  WizardCancelParams: WizardCancelParamsSchema,
  WizardStatusParams: WizardStatusParamsSchema,
  WizardStep: WizardStepSchema,
  WizardNextResult: WizardNextResultSchema,
  WizardStartResult: WizardStartResultSchema,
  WizardStatusResult: WizardStatusResultSchema,

  // Realtime Talk client/session events and channel control payloads.
  TalkModeParams: TalkModeParamsSchema,
  TalkEvent: TalkEventSchema,
  TalkCatalogParams: TalkCatalogParamsSchema,
  TalkCatalogResult: TalkCatalogResultSchema,
  TalkClientCreateParams: TalkClientCreateParamsSchema,
  TalkClientCreateResult: TalkClientCreateResultSchema,
  TalkClientSteerParams: TalkClientSteerParamsSchema,
  TalkAgentControlResult: TalkAgentControlResultSchema,
  TalkClientToolCallParams: TalkClientToolCallParamsSchema,
  TalkClientToolCallResult: TalkClientToolCallResultSchema,
  TalkConfigParams: TalkConfigParamsSchema,
  TalkConfigResult: TalkConfigResultSchema,
  TalkSessionAppendAudioParams: TalkSessionAppendAudioParamsSchema,
  TalkSessionCancelOutputParams: TalkSessionCancelOutputParamsSchema,
  TalkSessionCancelTurnParams: TalkSessionCancelTurnParamsSchema,
  TalkSessionCreateParams: TalkSessionCreateParamsSchema,
  TalkSessionCreateResult: TalkSessionCreateResultSchema,
  TalkSessionJoinParams: TalkSessionJoinParamsSchema,
  TalkSessionJoinResult: TalkSessionJoinResultSchema,
  TalkSessionTurnParams: TalkSessionTurnParamsSchema,
  TalkSessionTurnResult: TalkSessionTurnResultSchema,
  TalkSessionSteerParams: TalkSessionSteerParamsSchema,
  TalkSessionSubmitToolResultParams: TalkSessionSubmitToolResultParamsSchema,
  TalkSessionCloseParams: TalkSessionCloseParamsSchema,
  TalkSessionOkResult: TalkSessionOkResultSchema,
  TalkSpeakParams: TalkSpeakParamsSchema,
  TalkSpeakResult: TalkSpeakResultSchema,
  ChannelsStatusParams: ChannelsStatusParamsSchema,
  ChannelsStatusResult: ChannelsStatusResultSchema,
  ChannelsStartParams: ChannelsStartParamsSchema,
  ChannelsStopParams: ChannelsStopParamsSchema,
  ChannelsLogoutParams: ChannelsLogoutParamsSchema,
  WebLoginStartParams: WebLoginStartParamsSchema,
  WebLoginWaitParams: WebLoginWaitParamsSchema,

  // Agent files, artifacts, model catalogs, commands, tools, and skill workshop.
  AgentSummary: AgentSummarySchema,
  AgentsCreateParams: AgentsCreateParamsSchema,
  AgentsCreateResult: AgentsCreateResultSchema,
  AgentsUpdateParams: AgentsUpdateParamsSchema,
  AgentsUpdateResult: AgentsUpdateResultSchema,
  AgentsDeleteParams: AgentsDeleteParamsSchema,
  AgentsDeleteResult: AgentsDeleteResultSchema,
  AgentsFileEntry: AgentsFileEntrySchema,
  AgentsFilesListParams: AgentsFilesListParamsSchema,
  AgentsFilesListResult: AgentsFilesListResultSchema,
  AgentsFilesGetParams: AgentsFilesGetParamsSchema,
  AgentsFilesGetResult: AgentsFilesGetResultSchema,
  AgentsFilesSetParams: AgentsFilesSetParamsSchema,
  AgentsFilesSetResult: AgentsFilesSetResultSchema,
  ArtifactSummary: ArtifactSummarySchema,
  ArtifactsListParams: ArtifactsListParamsSchema,
  ArtifactsListResult: ArtifactsListResultSchema,
  ArtifactsGetParams: ArtifactsGetParamsSchema,
  ArtifactsGetResult: ArtifactsGetResultSchema,
  ArtifactsDownloadParams: ArtifactsDownloadParamsSchema,
  ArtifactsDownloadResult: ArtifactsDownloadResultSchema,
  AgentsListParams: AgentsListParamsSchema,
  AgentsListResult: AgentsListResultSchema,
  ModelChoice: ModelChoiceSchema,
  ModelsListParams: ModelsListParamsSchema,
  ModelsListResult: ModelsListResultSchema,
  CommandEntry: CommandEntrySchema,
  CommandsListParams: CommandsListParamsSchema,
  CommandsListResult: CommandsListResultSchema,
  SkillsStatusParams: SkillsStatusParamsSchema,
  ToolsCatalogParams: ToolsCatalogParamsSchema,
  ToolCatalogProfile: ToolCatalogProfileSchema,
  ToolCatalogEntry: ToolCatalogEntrySchema,
  ToolCatalogGroup: ToolCatalogGroupSchema,
  ToolsCatalogResult: ToolsCatalogResultSchema,
  ToolsEffectiveParams: ToolsEffectiveParamsSchema,
  ToolsEffectiveEntry: ToolsEffectiveEntrySchema,
  ToolsEffectiveGroup: ToolsEffectiveGroupSchema,
  ToolsEffectiveNotice: ToolsEffectiveNoticeSchema,
  ToolsEffectiveResult: ToolsEffectiveResultSchema,
  ToolsInvokeParams: ToolsInvokeParamsSchema,
  ToolsInvokeError: ToolsInvokeErrorSchema,
  ToolsInvokeResult: ToolsInvokeResultSchema,
  SkillsBinsParams: SkillsBinsParamsSchema,
  SkillsBinsResult: SkillsBinsResultSchema,
  SkillsSearchParams: SkillsSearchParamsSchema,
  SkillsSearchResult: SkillsSearchResultSchema,
  SkillsDetailParams: SkillsDetailParamsSchema,
  SkillsDetailResult: SkillsDetailResultSchema,
  SkillsProposalsListParams: SkillsProposalsListParamsSchema,
  SkillsProposalsListResult: SkillsProposalsListResultSchema,
  SkillsProposalInspectParams: SkillsProposalInspectParamsSchema,
  SkillsProposalInspectResult: SkillsProposalInspectResultSchema,
  SkillsProposalCreateParams: SkillsProposalCreateParamsSchema,
  SkillsProposalUpdateParams: SkillsProposalUpdateParamsSchema,
  SkillsProposalReviseParams: SkillsProposalReviseParamsSchema,
  SkillsProposalRequestRevisionParams: SkillsProposalRequestRevisionParamsSchema,
  SkillsProposalRequestRevisionResult: SkillsProposalRequestRevisionResultSchema,
  SkillsProposalActionParams: SkillsProposalActionParamsSchema,
  SkillsProposalApplyResult: SkillsProposalApplyResultSchema,
  SkillsProposalRecordResult: SkillsProposalRecordResultSchema,
  SkillsSecurityVerdictsParams: SkillsSecurityVerdictsParamsSchema,
  SkillsSecurityVerdictsResult: SkillsSecurityVerdictsResultSchema,
  SkillsSkillCardParams: SkillsSkillCardParamsSchema,
  SkillsSkillCardResult: SkillsSkillCardResultSchema,
  SkillsUploadBeginParams: SkillsUploadBeginParamsSchema,
  SkillsUploadChunkParams: SkillsUploadChunkParamsSchema,
  SkillsUploadCommitParams: SkillsUploadCommitParamsSchema,
  SkillsInstallParams: SkillsInstallParamsSchema,
  SkillsUpdateParams: SkillsUpdateParamsSchema,

  // Scheduler, logs, approval, plugin control, device, chat, and lifecycle events.
  CronJob: CronJobSchema,
  CronListParams: CronListParamsSchema,
  CronStatusParams: CronStatusParamsSchema,
  CronGetParams: CronGetParamsSchema,
  CronAddParams: CronAddParamsSchema,
  CronUpdateParams: CronUpdateParamsSchema,
  CronRemoveParams: CronRemoveParamsSchema,
  CronRunParams: CronRunParamsSchema,
  CronRunsParams: CronRunsParamsSchema,
  CronRunLogEntry: CronRunLogEntrySchema,
  LogsTailParams: LogsTailParamsSchema,
  LogsTailResult: LogsTailResultSchema,
  ExecApprovalsGetParams: ExecApprovalsGetParamsSchema,
  ExecApprovalsSetParams: ExecApprovalsSetParamsSchema,
  ExecApprovalsNodeGetParams: ExecApprovalsNodeGetParamsSchema,
  ExecApprovalsNodeSetParams: ExecApprovalsNodeSetParamsSchema,
  ExecApprovalsSnapshot: ExecApprovalsSnapshotSchema,
  ExecApprovalGetParams: ExecApprovalGetParamsSchema,
  ExecApprovalRequestParams: ExecApprovalRequestParamsSchema,
  ExecApprovalResolveParams: ExecApprovalResolveParamsSchema,
  PluginApprovalRequestParams: PluginApprovalRequestParamsSchema,
  PluginApprovalResolveParams: PluginApprovalResolveParamsSchema,
  PluginControlUiDescriptor: PluginControlUiDescriptorSchema,
  PluginsSessionActionFailureResult: PluginsSessionActionFailureResultSchema,
  PluginsSessionActionParams: PluginsSessionActionParamsSchema,
  PluginsSessionActionResult: PluginsSessionActionResultSchema,
  PluginsSessionActionSuccessResult: PluginsSessionActionSuccessResultSchema,
  PluginsUiDescriptorsParams: PluginsUiDescriptorsParamsSchema,
  PluginsUiDescriptorsResult: PluginsUiDescriptorsResultSchema,
  DevicePairListParams: DevicePairListParamsSchema,
  DevicePairApproveParams: DevicePairApproveParamsSchema,
  DevicePairRejectParams: DevicePairRejectParamsSchema,
  DevicePairRemoveParams: DevicePairRemoveParamsSchema,
  DeviceTokenRotateParams: DeviceTokenRotateParamsSchema,
  DeviceTokenRevokeParams: DeviceTokenRevokeParamsSchema,
  DevicePairRequestedEvent: DevicePairRequestedEventSchema,
  DevicePairResolvedEvent: DevicePairResolvedEventSchema,
  ChatHistoryParams: ChatHistoryParamsSchema,
  ChatMetadataParams: ChatMetadataParamsSchema,
  ChatMessageGetParams: ChatMessageGetParamsSchema,
  ChatMessageGetResult: ChatMessageGetResultSchema,
  ChatSendParams: ChatSendParamsSchema,
  ChatAbortParams: ChatAbortParamsSchema,
  ChatInjectParams: ChatInjectParamsSchema,
  ChatDeltaEvent: ChatDeltaEventSchema,
  ChatFinalEvent: ChatFinalEventSchema,
  ChatAbortedEvent: ChatAbortedEventSchema,
  ChatErrorEvent: ChatErrorEventSchema,
  ChatEvent: ChatEventSchema,
  UpdateStatusParams: UpdateStatusParamsSchema,
  UpdateRunParams: UpdateRunParamsSchema,
  TickEvent: TickEventSchema,
  ShutdownEvent: ShutdownEventSchema,
} satisfies Record<string, TSchema>;

export {
  MIN_CLIENT_PROTOCOL_VERSION,
  MIN_PROBE_PROTOCOL_VERSION,
  PROTOCOL_VERSION,
} from "../version.js";
